### ISSUE TITLE
Errors in example

### ISSUE THREAD

**Issue by AKomaromy** [alteryx/ui-automation-samples#4]
I get the following errors after installing the tools and trying to run the example. I tried installing pywinauto separately with no luck. Any tips?

	Designer x64	Started running C:\Users\Andrew Komaromy\Downloads\EAG\Alteryx\ui-automation-samples-master\Examples\AlteryxGUIAutomation.yxmd at 06/12/2018 16:29:19
	GUI Start Exe (1)	Traceback (most recent call last):¶  File "GUIStartExeEngine.py", line 11, in <module>¶ModuleNotFoundError: No module named 'pywinauto'¶
	GUI Click (19)	Traceback (most recent call last):¶  File "GUIClickEngine.py", line 12, in <module>¶ModuleNotFoundError: No module named 'pywinauto'¶
	GUI Click (20)	Traceback (most recent call last):¶  File "GUIClickEngine.py", line 12, in <module>¶ModuleNotFoundError: No module named 'pywinauto'¶
	GUI Keyboard (26)	Traceback (most recent call last):¶  File "GUIKeyboardEngine.py", line 11, in <module>¶ModuleNotFoundError: No module named 'pywinauto'¶
	GUI Keyboard (27)	Traceback (most recent call last):¶  File "GUIKeyboardEngine.py", line 11, in <module>¶ModuleNotFoundError: No module named 'pywinauto'¶
	GUI Get Info (28)	Traceback (most recent call last):¶  File "GUIGetInfoEngine.py", line 11, in <module>¶ModuleNotFoundError: No module named 'pywinauto'¶
	Designer x64	Finished running AlteryxGUIAutomation.yxmd in 0.3 seconds with 6 errors

**Comment by Ninjef** [comment]
Hey @AKomaromy. What version of Alteryx Designer are you running?

**Comment by Ninjef** [comment]
Perhaps I should make the documentation more clear. These only work on Designer 2018.1+
If it's not working on 2018.1, please let me know! Upgrading may help.

**Comment by AKomaromy** [comment]
I am using 11.7. I was under the impression that 11.7 is the same as 18.1 except with a difference in the licensing. Maybe I'm mistaken. I look forward to trying it when I get 18.1. Thank you very much for sharing this.
________________________________

**Comment by Ninjef** [comment]
No problem @AKomaromy. Let me know if you need anything else.
